name: "[ACTION] Auto Version"

description: '自动生成 VERSION.md 文件'

runs:
  using: composite
  steps:
    # - name: "[STEP] Run Git Info via Action"
    #   uses: ./.github/actions/git-info

    - name: "[STEP] Run Worker via Bash"
      shell: bash
      run: bash ${{ github.action_path }}/worker.bash
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}

    - name: "[STEP] Install dependencies"
      shell: bash
      run: pip install -r ${{ github.action_path }}/pylib.txt
    
    - name: "[STEP] Run Worker via Python"
      shell: bash
      run: python ${{ github.action_path }}/worker.py
      env:
        ACTION_PATH: ${{ github.action_path }}

      