name: "[ACTION] Auto Version"

description: '自动生成 VERSION.md 文件'

runs:
  using: composite
  steps:
    - name: "[STEP] Run Worker via Bash"
      shell: bash
      run: bash ${{ github.action_path }}/worker.bash
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}

    - name: "[STEP] Run Worker via Python"
      id: worker
      shell: bash
      run: python ${{ github.action_path }}/worker.py
      env:
        ACTION_PATH: ${{ github.action_path }}

    - name: "[STEP] Print Summary (No Changed)"
      if: steps.worker.outputs.has_changes == 'false'
      uses: ./.github/actions/bot-summary
      with:
        title: "Auto Version"
        message: "No Changed"

    - name: "[STEP] Print Summary (Has Changed)"
      if: steps.worker.outputs.has_changes == 'true'
      uses: ./.github/actions/bot-summary
      with:
        title: "Auto Version"
        message: "Folder Count = ${{ steps.worker.outputs.folder_count }}, File Count = ${{ steps.worker.outputs.file_count }}, Total Size = ${{ steps.worker.outputs.size_hr }}"

