name: "[ACTION] Bot Summary"
# .github/actions/bot-summary/action.yml

description: 输出 Summary 信息

inputs:

  title:
    description: '标题'
    required: true

  message:
    description: '要输出的信息'
    required: true

runs:
  using: composite
  steps: 
    # - name: "[STEP] Output Summary Information via Command"
    #   shell: bash
    #   run: |
    #     TIME="$(date '+%F %T') (UTC)"
    #     SUMMARY="[${{ inputs.title }}] ${TIME}: ${{ inputs.message }}"
    #     echo "${SUMMARY}" >> $GITHUB_STEP_SUMMARY
    #     echo "$SUMMARY"
    - name: "[STEP] Run Bot Summary via Bash"
      run: bash ${{ github.action_path }}/worker.bash
      shell: bash
      env:
        TITLE: ${{ inputs.title }}
        MESSAGE: ${{ inputs.message }}
