name: "[ACTION] Auto Readmes"

description: '自动生成 README.md 文件'

runs:
  using: composite
  steps:
    - name: "[STEP] Run Worker via Python"
      run: python ${{ github.action_path }}/worker.py
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}

    - name: "[STEP] Print Summery"
      uses: ./.github/actions/bot-summary
      with:
        title: "Auto Readmes"
        message: "Scanned ${{ env.TOTAL_SCANNED }} Files, Modified ${{ env.TOTAL_MODIFIED }} Files." 