name: "[ACTION] Auto Readmes"

description: '自动生成 README.md 文件'

runs:
  using: composite
  steps:
    - name: "[Step] Run Pip Dependencies via Action"
      uses: ./.github/actions/pip-dependencies
      
    - name: "[STEP] Run Worker via Python"
      run: python ${{ github.action_path }}/worker.py
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}