name: 01. Auto Contents

description: '自动生成 CONTENTS.md 文件'

runs:
  using: composite
  steps:
    - name: 运行 Python 脚本生成所有 CONTENTS.md
      run: python .github/scripts/auto-contents.py
      shell: bash