name: "[ACTION] Auto Contents"

description: '自动生成 CONTENTS.md 文件'

runs:
  using: composite
  steps:
    - name: "[STEP] Push Cache Module"
      uses: actions/cache@main
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/pylib.txt') }}
        restore-key: ${{ runner.os }}-pip-

    - name: "[STEP] Install dependencies"
      shell: bash
      run: pip install -r ${{ github.action_path }}/pylib.txt
      
    - name: "[STEP] Run Worker via Python"
      run: python ${{ github.action_path }}/worker.py
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}