name: "[ACTION] Auto Contents"

description: 'Auto add License'

runs:
  using: composite
  steps:
    - name: "[STEP] Run Worker via Python"
      run: python ${{ github.action_path }}/worker.py
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}

    - name: "[STEP] Print Summary"
      uses: ./.github/actions/bot-summary
      with:
        title: "Auto License"
        message: "Scanned ${{ env.TOTAL_SCANNED }} Files, Modified ${{ env.TOTAL_MODIFIED }} Files." 