name: "[ACTION] Auto Contents"

description: 'Auto add License'

runs:
  using: composite
  steps:
    - name: "[STEP] Install dependencies"
      shell: bash
      run: pip install -r ${{ github.action_path }}/pylib.txt
      
    - name: "[STEP] Run Worker via Python"
      run: python ${{ github.action_path }}/worker.py
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}