name: "[ACTION] Auto Contents"
# .github/actions/auto-license/action.yml

description: 'Auto add License'

inputs:
  patterns:
    description: '要匹配的文件模式表达式（每行一个）'
    required: true

runs:
  using: composite
  steps:
    - name: "[STEP] Run Bot Patterns via Action"
      id: glob
      uses: ./.github/actions/bot-patterns
      with:
        patterns: ${{ inputs.patterns }}

    - name: "[STEP] Run Worker via Python"
      run: python ${{ github.action_path }}/worker.py
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}
        FILES: ${{ steps.glob.outputs.files }}

    - name: "[STEP] Print Summary via Action"
      uses: ./.github/actions/bot-summary
      with:
        title: "Auto License"
        message: "Scanned ${{ env.TOTAL_FOLDERS }} Files, Modified ${{ env.TOTAL_UPDATES }} Files." 