name: "[ACTION] Developing Test"
# .github/actions/dev-test/action.yml

description: '开发测试'

inputs:
  patterns:
    description: '要匹配的文件模式表达式（每行一个）'
    required: true

outputs:
  files:
    description: "匹配到的文件列表"
    value: ${{ steps.glob.outputs.paths }}
    
runs:
  using: composite
  steps:
  
    - name: "[STEP] Run Glob files via Action"
      id: glob
      uses: tj-actions/glob@main
      with:
        files: ${{ inputs.patterns }}        

    - name: "[STEP] Print Glob Result via Command"
      shell: bash
      run: |
        echo "匹配到的文件列表：${{ steps.glob.outputs.paths }}"
        echo "================================"
        echo ${{ steps.glob.outputs.paths }} | tr ' ' '\n' | while IFS= read -r file
        do
          if [ -n $"file" ]
          then
            echo "处理文件：$file"
          fi
        done
        echo "================================"
