name: "[ACTION] Developing Test"
# .github/actions/dev-test/action.yml

description: '开发测试'

inputs:
  to:
    description: "收件人，逗号分割"
    required: true
  
  subject:
    description: "邮件主题"
    required: true

  ishtml:
    description: "是否为HTML邮件，默认为 True"
    required: false
    default: true
  
  body:
    description: "邮件正文"
    required: false
    default: "<!-- No Body -->"

  
    
runs:
  using: composite
  steps:
    - name: "[STEP] Run Send Email via Action"
      id: worker
      uses: dawidd6/action-send-mail@master
      with:
        server_address: ${{ env.server_address }}
        server_port: ${{ env.server_port }}
        secure: ${{ env.secure }}
        ignore_cert: ${{ env.ignore_cert }}
        convert_markdown: ${{ env.convert_markdown }}
        username: ${{ env.username }}
        password: ${{ env.password }}
        from: ${{ env.smtp_from }}
        to: ${{ inputs.to }}
        subject: ${{ inputs.subject }}
        body: ${{ inputs.ishtml == 'true' && '' || inputs.body }}
        html_body: ${{ inputs.ishtml == 'true' && inputs.body || '' }}
  
