name: "[ACTION] Git Info"

description: Load Git Info

runs:
  using: composite
  steps:
    - name: "[STEP] Run Worker via Bash"
      run: bash ${{ github.action_path }}/worker.bash
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}

    - name: "[STEP] Print Summary"
      uses: ./.github/actions/bot-summary
      with:
        title: "Git Info"
        message: "Loaded ${{ env.CONFIG_COUNT }} Configurations."