name: "[ACTION] Bot Patterns"
# .github/actions/bot-patterns/action.yml

description: '模式匹配文件列表'

inputs:
  patterns:
    description: '要匹配的文件模式表达式（每行一个）'
    required: true
  
  separator:
    description: '输出结果分隔符，默认逗号“,”'
    required: false
    default: ","
  
  debug:
    description: '输出匹配结果'
    required: false
    default: false

outputs:
  files:
    description: "匹配到的文件列表"
    value: ${{ steps.glob.outputs.paths }}
    
runs:
  using: composite
  steps:  
    - name: "[STEP] Run Glob files via Action"
      id: glob
      uses: tj-actions/glob@main
      with:
        separator: ${{ inputs.separator }}
        files: ${{ inputs.patterns }}    
    
    - name: "[STEP] Print Glob Result via Command"
      if: ${{ inputs.debug == 'true' }}
      shell: bash
      run: ${{ github.action_path }}/debug.bash
      env:
        SEPARATOR: ${{ inputs.separator }}
        PATTERNS: ${{ inputs.patterns }}
        FILES: ${{ steps.glob.outputs.paths }}
        
