name: "[ACTION] Auto Readmes (Root)"
# .github/actions/auto-readmes-root/action.yml

description: '自动生成 README.md 文件 （仅根文件夹）'

runs:
  using: composite
  steps:
    - name: "[STEP] Run Worker via Python"
      id: worker
      run: python ${{ github.action_path }}/worker.py
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}
    
    - name: "[STEP] Print Summary via Action"
      id: bot-summary
      uses: ./.github/actions/bot-summary
      with:
        title: "Auto Readme (Root)"
        message: ${{ env.README_STATUS }}