name: "[ACTION] Auto Readmes (Root)"

description: '自动生成 README.md 文件 （仅根文件夹）'

runs:
  using: composite
  steps:
    - name: "[STEP] Run Worker via Python"
      run: python ${{ github.action_path }}/worker.py
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}