name: "[WORKFLOW] Auto MDLint"

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write

jobs:
  auto-mdlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Auto MDLint
        uses: ./.github/actions/auto-mdlint
        with:
          patterns: |
            **/*.md
            *.md

      - name: Run Git Commit
        uses: ./.github/actions/git-commit
        with:
          patterns: |
            **/*.md
            *.md
          commit-prefix: "Auto MDLint"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

