name: 03. Auto License

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write

jobs:
  add-license:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}        

      - name: 运行 Python 脚本添加License声明
        run: python .github/scripts/auto-license.py
      
      - name: Run Auto Commit
        uses: ./.github/actions/auto-commit
        with:
          patterns: |
            **/*.md
            *.md
          commit-prefix: "Auto License"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}