name: "[WORKFLOW] Auto License"

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write

jobs:
  add-license:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}        
      
      - name: Run Auto Dependencies via Action
        uses: ./.github/actions/auto-deps

      - name: Run Auto License
        uses: ./.github/actions/auto-license
      
      - name: Run Git Commit
        uses: ./.github/actions/git-commit
        with:
          patterns: |
            **/*.md
            *.md
          commit-prefix: "Auto License"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}