name: Auto Version

on:
    workflow_dispatch:
    workflow_call:

permissions:
    contents: write

jobs:
  auto-version:
    runs-on: ubuntu-latest

    steps:
      - name: Chekcout repository
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Auto Version
        uses: ./.github/actions/auto-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Auto Commit
        uses: ./.github/actions/auto-commit
        with:
          patterns: VERSION.md
          commit-prefix: Auto Version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}