name: "[WORKFLOW] Daily Operation"
# .github/workflow/daily-operation.yml

on:
  schedule:
    - cron: '30 16 * * *'
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  daily-operation:
    runs-on: ubuntu-latest
    
    steps:
      - name: "[STEP] Run Checkout Repository via Action"
        id: checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: "[STEP] Run Auto Dependencies via Action"
        id: auto-deps
        uses: ./.github/actions/auto-deps
      
      - name: "[STEP] Run Auto Contents via Action"
        id: auto-contents
        uses: ./.github/actions/auto-contents
        with:
          patterns: |
            **/*.md
            !README.md
            !CONTENTS.md
            !LICENSE.md
            !VERSION.md
            !.github/**
            !.git/**
            !.vscode/**

      - name: "[STEP] Run Auto Readmes via Action"
        id: auto-readmes
        uses: ./.github/actions/auto-readmes
        with:
          patterns: |
            !**/CONTENTS.md
            !**/README.md
            !.github/**
            !.git/**
            !.vscode/**

      - name: "[STEP] Run Auto License via Action"
        id: auto-license
        uses: ./.github/actions/auto-license
        with: 
          patterns: |
            **/*.md
            !**/README.md
            !**/LICENSE.md
            !**/CONTENTS.md
            !VERSION.md
            !Markdown*.md
            !.github/**
            !.git/**
            !.vscode/**

      - name: "[STEP] Run Auto MDLint via Action"
        id: auto-mdlint
        uses: ./.github/actions/auto-mdlint
        with:
          patterns: |
            **/*.md
            *.md

      - name: "[STEP] Run Git Commit via Action (Daily)"
        id: git-commit-daily  
        uses: ./.github/actions/git-commit
        with:
          patterns: |
            **/*.md
            *.md
            !VERSION.md
          commit-prefix: "Daily Markdown Fix"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "[STEP] Run Git Release via Action (Daily)"
        id: git-release-daily
        uses: ./.github/actions/git-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "[STEP] Run Auto Version via Action"
        id: auto-version
        uses: ./.github/actions/auto-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          patterns: |
            **/**
            !.vscode/**
            !.git/**
            !.github/**
            !VERSION.md

      - name: "[STEP] Run Auto Readmes via Action (Root)"
        id: auto-readmes-root
        uses: ./.github/actions/auto-readmes-root

      - name: "[STEP] Run Git Commit via Action (Version)"
        id: git-commit-version
        uses: ./.github/actions/git-commit
        with:
          patterns: |
            README.md
            VERSION.md
          commit-prefix: "Daily Version Update"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "[STEP] un Git Release via Action (Version)"
        id: git-release-version
        uses: ./.github/actions/git-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
