name: "[WORKFLOW] Daily Operation (Scheduled)"

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  daily-markdown-fix:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Run Auto Contents
        uses: ./.github/actions/auto-contents

      - name: Run Auto Readmes
        uses: ./.github/actions/auto-readmes

      - name: Run Auto License
        uses: ./.github/actions/auto-license

      - name: Run Auto MDLint
        uses: ./.github/actions/auto-mdlint

      - name: Run Auto Commit
        uses: ./.github/actions/git-commit
        with:
          patterns: |
            **/*.md
            *.md
          commit-prefix: "Daily Operation"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Auto Release
        uses: ./.github/actions/git-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  daily-version-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Auto Version
        uses: ./.github/actions/auto-version

      - name: Run Auto Readmes
        uses: ./.github/actions/auto-readmes
      
      - name: Run Auto Commit for Version
        uses: ./.github/actions/git-commit
        with:
          patterns: |
            VERSION.md
          commit-prefix: "Daily Version Check"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Auto Release
        uses: ./.github/actions/git-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
