name: "[WORKFLOW] Developing Test"
# .github/workflows/dev-test.yml

on:
  workflow_dispatch:

# permissions: read-all
# permissions: write-all
permissions:
  actions: read                 # read|write|none，处理 GitHub Actions。
  artifact-metadata: read       # read|write|none，处理构件元数据。
  attestations: read            # read|write|none，处理构件证明。
  checks: read                  # read|write|none，处理检查运行和检查套件。
  contents: read                # read|write|none，处理仓库内容。
  deployments: read             # read|write|none，处理部署。
  discussions: write            # read|write|none，处理 GitHub Discussions。
  id-token: none                #     |write|none，获取 OpenID Connect (OIDC) 令牌。
  issues: read                  # read|write|none，处理议题。
  models: read                  # read|     |none，使用 GitHub Models 生成人工智能推理响应。
  packages: read                # read|write|none，处理 GitHub Packages。
  pages: read                   # read|write|none，处理 GitHub Pages。
  pull-requests: read           # read|write|none，处理拉取请求。
  security-events: read         # read|write|none，处理 GitHub 代码扫描警报。
  statuses: read                # read|write|none，处理提交状态。
  vulnerability-alerts: read    # read|     |none，读取 Dependabot 警报。

jobs:
  dev-test:
    runs-on: ubuntu-latest

    steps:
      # - name: "[STEP] Run Checkout Repository via Action"
      #   id: checkout
      #   uses: actions/checkout@main
      #   with:
      #     fetch-depth: 0
      #     token: ${{ secrets.GITHUB_TOKEN }}

      # - name: "[STEP] Run Developing Test via Action"
      #   uses: ./.github/actions/dev-test
      #   id: glob
      #   with:
      #     patterns: |
      #       .github/**/*.py

      - name: "[STEP] Send Email via Action"
        uses: ./.github/action/dev-test
        env:
          server_address: ${{ vars.SMTP_SERVER_ADDRESS }}
          server_port: ${{ vars.SMTP_SERVER_PORT }}
          secure: ${{ vars.SMTP_SECURE }}
          ignore_cert: ${{ vars.SMTP_IGNORE_CERT }}
          convert_markdown: ${{ vars.SMTP_CONVERT_MARKDOWN }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD}}
          to: "godners@163.com"
          subject: "test-from-action"
          ishtml: "false"
          body: "test on test"

      # - name: "[STEP] Print Summary via Action"
      #   id: bot-summary
      #   uses: ./.github/actions/bot-summary
      #   with:
      #     title: "Developing Test"
      #     message: "MESSAGE-MESSAGE-MESSAGE"
