name: "[WORKFLOW] Git Release"

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Run Auto Release
        uses: ./.github/actions/git-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          