name: TEST. Git Info

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  git-info:
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v6
      #   with:
      #     fetch-depth: 0
      #     token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout repository
        uses: ./.github/actions/checkout

      - name: run bash
        run: bash .github/scripts/auto-commit-info.bash
        shell: bash

      - name: verify git config
        run: git config --local --list
        shell: bash
        

        