name: "[WORKFLOW] Git Commit"

on: 
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Auto Dependencies via Action
        uses: ./.github/actions/auto-deps          
          
      - name: Run Auto Commit
        uses: ./.github/actions/git-commit
        with:
          patterns: |
            **/*.md
            *.md
            **/*.json
            **/*.bash
            **/*.yml
            **/*.py
          commit-prefix: "[TEST] Auto Commit"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}