name: TEST. Auto Commit

on: 
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Make some changes
        shell: bash
        run: echo "- $(date -u -d '8 hours' '+%F %T')" >> .github/resources/auto-commit-test.md
      
      - name: Run Auto Commit
        uses: ./.github/actions/auto-commit
        with:
          patterns: |
            **/*.md
            *.md
            **/*.json
            **/*.bash
            **/*.yml
            **/*.py
          commit-prefix: "[TEST] Auto Commit"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}